package:
  name: gnsstk-apps
  version: {{ environ.get('GIT_LAST_TAG', 'v0.0.0')[1:] }}

source:
  path: ../

build:
  number: {{ environ.get('GIT_CHANGES_LAST_TAG', 0) }}
  script_env:
    - GIT_COMMIT

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
  host:
    - gnsstk >=13.0.0,<14
  run:
    - gnsstk >=13.0.0,<14

test:
  imports:
    - gnsstk

about:
  home: https://sgl-git.arlut.utexas.edu:sgl-tks/gnsstk-apps
  summary: The GNSS Toolkit Applications (GNSSTk-Apps)
  description: |
    The GNSS Toolkit (GNSSTk) is an open-source (LGPL) project sponsored by
    the Space and Geophysics Laboratory (SGL).
