{% set build_user = environ.get('CI_USER', '') %}
{% set build_token = environ.get('CI_TOKEN', '') %}


package:
  name: gpstk-apps
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'v0.0')[1:] }}

source:
  git_rev: {{ environ.get('GIT_COMMIT', 'main') }}
  git_url: https://{{build_user}}:{{build_token}}@sgl-git.arlut.utexas.edu/sgl-tks/gpstk-apps.git

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script_env:
    - GIT_COMMIT

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
  host:
    - python {{ python }}
    - setuptools
    - gpstk >=12.0.0,<13
  run:
    - python {{ python }}
    - gpstk >=12.0.0,<13

test:
  imports:
    - gpstk

about:
  home: https://sgl-git.arlut.utexas.edu:sgl-tks/gpstk-apps
  summary: The GPS Toolkit Applications (GPSTk-Apps)
  description: |
    The GPS Toolkit (GPSTk) is an open-source (LGPL) project sponsored by
    the Space and Geophysics Laboratory (SGL).
