{% set build_user = environ.get('CI_USER', '') %}
{% set build_token = environ.get('CI_TOKEN', '') %}


package:
  name: gnsstk-apps
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'v0.0')[1:] }}

source:
  git_rev: {{ environ.get('GIT_COMMIT', 'main') }}
  git_url: https://{{build_user}}:{{build_token}}@sgl-git.arlut.utexas.edu/sgl-tks/gnsstk-apps.git

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script_env:
    - GIT_COMMIT

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
  host:
    - python {{ python }}
    - setuptools
    - gnsstk >=12.0.0,<13
  run:
    - python {{ python }}
    - gnsstk >=12.0.0,<13

test:
  imports:
    - gnsstk

about:
  home: https://sgl-git.arlut.utexas.edu:sgl-tks/gnsstk-apps
  summary: The GNSS Toolkit Applications (GNSSTk-Apps)
  description: |
    The GNSS Toolkit (GNSSTk) is an open-source (LGPL) project sponsored by
    the Space and Geophysics Laboratory (SGL).
